export const API_HOS_URL = "http://localhost:3000"
export const METHOD_POST = "/post"
export const METHOD_PUT = "/put"
export const METHOD_PATCH = "/patch"
export const METHOD_GET = "/get"
export const METHOD_UPDATE = "/update"
export const METHOD_DELETE = "/delete"